# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: jdkent/eprime_convert:latest

    working_directory: ~/repo

    steps:
      - run:
          name: clone github repo
          command: |
            git clone https:///${GITHUB_TOKEN}@github.com/HBClab/BetterFlanker.git
      - run:
          name: check if data QA should be skipped
          command: |
            cd ~/repo/BetterFlanker
            if [[ "$( git log --format=oneline -n 1 $CIRCLE_SHA1 | grep -i -E '\[skip[ _]?ci\]' )" != "" ]]; then
              echo "Skipping Data QA"
              circleci step halt
            fi
      - run:
          name: run eprime convert
          command: |
              source activate eprime_convert
              ~/repo/BetterFlanker/code/eprime_convert.py \
                -b ~/repo/BetterFlanker/bids \
                -r ~/repo/BetterFlanker \
                -c ~/repo/BetterFlanker/code/task.json \
                --sub-prefix GE120
      - run:
          name: add and commit files
          command: |
            cd ~/repo/BetterFlanker
            git config credential.helper 'cache --timeout=120'
            git config user.email "helper@help.com"
            git config user.name "QA Bot"

            # check to see if there were any changes to the repository.
            if [ -z "$(git ls-files --other --exclude-standard --directory)" ]; then
              echo "No files to be committed!"
            else
              # Push quietly to prevent showing the token in log
              git add .
              git commit -m "[skip ci] $(date)"
              git push -q https://${GITHUB_TOKEN}@github.com/HBClab/BetterFlanker.git master
            fi

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          context: behav_pipelines
